version: '3.7'

services:
    mongo:
        container_name: mongodb-service
        image: mongo
        env_file: secrets.env
        environment:
            # provide your credentials here
            - MONGO_INITDB_ROOT_USERNAME=root
            # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - ./host-data/mongo-data:/data/db
            - ./docker/mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
            # - ./docker/mongo/mongod.conf:/etc/mongod.conf   USE FOR REPLICASET INSTALLATIONS
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
            interval: 10s
            start_period: 30s
        # command: ["-f", "/etc/mongod.conf", "--replSet", "secluded", "--bind_ip_all"]    USE FOR REPLICASET INSTALLATIONS
        # command: rm -rf /tmp/mongodb-27017.sock || true
        ports:
            - '27017:27017'
        restart: unless-stopped

    redis:
        container_name: redis-service
        image: redis:7.2.4-alpine
        # restart: unless-stopped
        ports:
            - '6379:6379'
        command:
            - /bin/sh
            - -c
            - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}" # Run as privileged to allow the container to change the vm.overcommit_memory setting
        privileged: true
        env_file:
            - secrets.env
        volumes:
            # - ./docker/redis/script.sh:/script.sh:r
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:r
            - ./host-data/redis-data:/data/redis:rw
        healthcheck:
            test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
            interval: 10s
            start_period: 30s

volumes:
    mongo_data:
        external: true
    monitoring:
        driver: bridge
